# Generated by Django 3.2 on 2022-03-28 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploading', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebook',
            old_name='image',
            new_name='photo',
        ),
    ]
